{{- if .Values.serviceaccount.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-loop.fullname" . }}
  labels:
    {{- include "webapp-loop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webapp-loop.selectorLabels" . | nindent 4 }}
{{- end }}    
